### ISSUE TITLE
Add -level options.

### ISSUE THREAD

**Issue by prgres** [kitagry/gtree#17]
I would like to use `gtree` as an alternative to `tree` but it misses one crucial functionality for me which exists in `tree`.
Would be great if you could add -level/-L flag to specify how deep the `gtree` should print.

For example: 

there is a root folder dir0 which contains file1, file2 and dir1
```
dir0
|
- dir1
    | 
    - file9
    - file8
- file1
- file2
```
Right now, gtree prints the whole structure, but with `-L 1` flag it could print only dir1, file1, file2 without nested file9 and file8.

**Comment by kitagry** [comment]
@prgres 

Thank you for the nice reporting!
I added `--level` (`-L`) option with #18 .

**Comment by prgres** [comment]
@kitagry thanks! works like a charm
